### PR TITLE
default: add amdgpu to RUNTIME_PM_DRIVER_BLACKLIST

### PR DESCRIPTION
**Pull request by yuq**
amdgpu is a relatively new open source kernel driver for AMD GPUs.

### CODE REVIEW

**Comment by linrunner** [comment]
Hi, could you explain why this driver must be blacklisted?

**Comment by yuq** [comment]
Hi, need your confirm:
driver **not** listed in RUNTIME_PM_DRIVER_BLACKLIST will still be power on when AC power mode
even in idle state (runtime PM disabled).

If so, amdgpu is like radeon and nouveau, still need runtime PM when AC power mode to turn itself
off when idle. (amdgpu is a new AMD GPU driver to support new AMD GPU hardware while radeon
only support older ones)

**Comment by linrunner** [comment]
Thanks for your explanation.

Blacklisted driver means that TLP won't touch Runtime PM at all for the device e.g. the actual state  on/auto will be determined at boot time by the driver. Does your device show "auto" after boot?

**Comment by yuq** [comment]
It's on by:
RUNTIME_PM_ON_AC=on

**Comment by linrunner** [comment]
Sorry, i didn't mean your setting. It is irelevant when the driver is blacklisted.

I meant the actual state of the device after boot. It is shown in the output of tlp-stat -e.

**Comment by yuq** [comment]
Here is the output of tlp-stat -e:

When battary mode
/sys/bus/pci/devices/0000:01:00.0/power/control = auto (0x030000, VGA compatible controller, amdgpu)

When AC power mode
/sys/bus/pci/devices/0000:01:00.0/power/control = on   (0x030000, VGA compatible controller, amdgpu)

**Comment by linrunner** [comment]
Please show the outputs with RUNTIME_PM_DRIVER_BLACKLIST="amdgpu" configured.

**Comment by yuq** [comment]
When RUNTIME_PM_DRIVER_BLACKLIST="amdgpu"

When battary mode
/sys/bus/pci/devices/0000:01:00.0/power/control = auto (0x030000, VGA compatible controller, amdgpu)

AC power mode
/sys/bus/pci/devices/0000:01:00.0/power/control = auto (0x030000, VGA compatible controller, amdgpu)

**Pull request merged**
