### PR TITLE
New output flags for tlp-stat to improve usability with other scripts

### PR DESCRIPTION
**Pull request by benjamin-voisin**
Add 3 new flags to tlp-stat : `-m`, `-q` and `--version`. The main goal being to facilitate the usage of tlp with other script, by making easier to parse outputs. All already existing outputs are unchanged, there are no retrocompatibility issues.

### New outputs

- The new flag `-m` (or `--mode`) output the status. This data was already available under the `-s` flag, but along with system informations. The output of `-s` is not modified. For example, it may output something like 
  ```
  --- TLP 1.7.0-alpha.0 --------------------------------------------
  
  +++ TLP Status
  State          = enabled
  RDW state      = disabled
  Last run       = 13:42:09, 2664 sec(s) ago
  Mode           = AC
  Power source   = AC
  ```
  When passed with the new `-q` quiet flag, it only output the current mode (`AC`, `battery`, `AC (manual)` or `battery (manual)`).
- The new flag `--version` simply output the current version, nothing else :
  ```
  1.7.0-alpha.0
  ```
- The new flag `-q` (or `--quiet`) removes the first line with version, and reduce the outputs for the `mode`, `temperature` and `cpu` outputs. The differences in `mode` is described above.
  For the temperature, if the results of `tlp-stat -t` is :
  ```
  --- TLP 1.7.0-alpha.0 --------------------------------------------
  
  +++ Temperatures
  CPU temp               =    49 [°C]
  Fan speed              = (not available)
  ```
  the result of `tlp-stat -t -q` will be :
  ```
  CPU temp               =    49 [°C]
  Fan speed              = (not available)
  ```
  
  For the cpu, if the reslut of `sudo tlp-stat -p` is :
  ```
  --- TLP 1.7.0-alpha.0 --------------------------------------------
  
  +++ Processor
  CPU model      = Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  
  /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = intel_pstate
  /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = powersave
  /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = performance powersave
  /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =   400000 [kHz]
  /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  4200000 [kHz]
  /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq  =   400000 [kHz]
  /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq  =  4200000 [kHz]
  /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference = balance_performance [EPP]
  /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences = default performance balance_performance balance_power power 
  
  /sys/devices/system/cpu/cpu1..cpu7: omitted for clarity, use -v to show all
  
  /sys/devices/system/cpu/intel_pstate/status            = active
  /sys/devices/system/cpu/intel_pstate/min_perf_pct      =   9 [%]
  /sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
  /sys/devices/system/cpu/intel_pstate/no_turbo          =   0
  /sys/devices/system/cpu/intel_pstate/hwp_dynamic_boost =   0
  /sys/devices/system/cpu/intel_pstate/turbo_pct         =  67 [%]
  /sys/devices/system/cpu/intel_pstate/num_pstates       =  39
  /sys/module/workqueue/parameters/power_efficient       = Y
  /proc/sys/kernel/nmi_watchdog                          = 0
  
  +++ Platform Profile
  /sys/firmware/acpi/platform_profile                    = (not available)
  /sys/firmware/acpi/platform_profile_choices            = (not available)
  ```
  the result of `sudo tlp-stat -p -q` will be :
  ```
  /sys/devices/system/cpu/intel_pstate/status            = active
  /sys/devices/system/cpu/intel_pstate/min_perf_pct      =   9 [%]
  /sys/devices/system/cpu/intel_pstate/max_perf_pct      = 100 [%]
  /sys/devices/system/cpu/intel_pstate/no_turbo          =   0
  /sys/devices/system/cpu/intel_pstate/hwp_dynamic_boost =   0
  /sys/devices/system/cpu/intel_pstate/turbo_pct         =  67 [%]
  /sys/devices/system/cpu/intel_pstate/num_pstates       =  39
  /sys/module/workqueue/parameters/power_efficient       = Y
  /proc/sys/kernel/nmi_watchdog                          = 0
  
  +++ Platform Profile
  /sys/firmware/acpi/platform_profile                    = (not available)
  /sys/firmware/acpi/platform_profile_choices            = (not available)
  ```

### Docs

The manpage and the help output for `tlp-stat` are updated accordingly to what is described above.

### CODE REVIEW

**Comment by linrunner** [comment]
Hi,

**Comment by benjamin-voisin** [comment]
I have updated the auto-completion, and fixed the indentation to 4 spaces.

> Do you realize that the formatting can change at any time and your scraping will no longer work?

That is why I think an easy way to get the version is useful, and it will always be much more futurproof than trying to parse the output with `grep` and `sed`.

>  I'm also curious: what are these "other scripts" - what is your use case?

I'm making a waybar module to see the current tlp status, and to be able to change

**Comment by linrunner** [comment]
I notice that `-s -q` and `-m` produce the same output, i.e. they are redundant. I will remove **-m** if you agree.

**Comment by benjamin-voisin** [comment]
I find it kinda weird that the `-s` flag output two informations : system infos and status infos. To my, It would be preferable to remove status infos from `-s` and put it only in the `-m` flag. My idea is :
- `-m` output the status infos
- `-m -q` output just the current tlp mode (bat, ac, bat (manual), ac (manual))
- `-s` output only system infos
- `-s -q` doesn't really matter, probably not different than `-s`

The main intention of my PR is to access easily the current mode (`-m -q`) and the version (`--version`). Maybe we remove the `-m` flag, and make `-s -q` output just the current status, but it feels weird to me (the fact that `-s` output system and status infos feels weird).
I did not change `-s` by fear that it might break retrocompatibility, but ideally I think `-s` should only output system infos, and `-m` status infos.
What do you think ?

**Comment by linrunner** [comment]
The scope of -s (system and status) has been stable for a long time, I don't want to change it. I wouldn't call it "weird" but "legacy".

> The main intention of my PR is to access easily the current mode and the version.

Then my suggestion is to implement just this:

* `-m` output just the current tlp mode - bat, ac, bat (manual), ac (manual)
* `--version`
* `-q` or `-quiet` removes the first line with version, and reduces the outputs for the temperature and cpu outputs

**Comment by benjamin-voisin** [comment]
Works good for me :+1:

**Comment by linrunner** [comment]
I have implemented my suggestions in my branch https://github.com/linrunner/TLP/tree/pr/729. Beyond `-q` no longer suppresses the entire output, but only the corresponding parts of cpu and temperatures.

Please check if this still meets your requirements.

**Comment by benjamin-voisin** [comment]
I'v tried it and it good for me, thanks !

**Comment by linrunner** [comment]
Further fixes and additions were necessary. The whole thing is merged to main now.

Thank you very much for your contribution.

**Pull request closed without merging**
