### PR TITLE
add support for amdgpu

### LINKED ISSUE #498: amdgpu and mobility integrated graphics
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)
[x] I've attached all required `tlp-stat` outputs (see below)

**Describe the bug**

change amd graphics settings in tlp for AC and battery doesn't work for amd integrated graphics
Mine laptop has ryzen 7 3700U

**Expected behavior**

change
/etc/tlp.d/graficos.conf L0043: RADEON_DPM_PERF_LEVEL_ON_AC="auto"
/etc/tlp.d/graficos.conf L0044: RADEON_DPM_PERF_LEVEL_ON_BAT="low"

would change the output of:

tlp bat
TLP started in battery mode (manual).
 cat /sys/class/drm/card0/device/power_dpm_force_performance_level 
auto

**To Reproduce**

config the desire perf dpm level in tlp and see that is not working.

1. Does the problem occur on battery or AC or both? both
2. Actions to reproduce the behaviour is answered already
3. Shell commands entered and their output
tlp bat
TLP started in battery mode (manual).
 cat /sys/class/drm/card0/device/power_dpm_force_performance_level 
auto
4. **Full output of `tlp-stat` via https://gist.github.com/ for *all*
   matching cases of 1.**
https://gist.github.com/userofryzen/831354948c4d2c25bdef2ca1e79e64ad
https://gist.github.com/userofryzen/9a239ad3f39afc08e43e9a99424c4af6
**Additional context**

### PR DESCRIPTION
**Pull request by mikk150**
Fixes #498

Tested on Lenovo Thinkpad T14 Gen 1 AMD version

### CODE REVIEW

**Comment by linrunner** [comment]
Thanks for your contribution.

I think I'll merge your code with set_radeon_profile() later and also add tlp-stat output.

**Comment by mikk150** [comment]
yep, set_radeon_profile() should have driver check as well, but since I do not have a card that uses radeon driver, I cannot really test it

**Comment by linrunner** [comment]
I did the merge. Could you please test the new  code?

Note that configuration for amdgpu is now done with RADEON_DPM_PERF_LEVEL_ON_AC/BAT too.

**Comment by linrunner** [comment]
ps. Please show the output of 

    tlp-stat -s -g

**Comment by mikk150** [comment]
```
--- TLP 1.4.0-alpha.0 --------------------------------------------

+++ System Info
System         = LENOVO ThinkPad T14 Gen 1 20UDCTO1WW
BIOS           = R1BET36W(1.05 )
Release        = "Manjaro Linux"
Kernel         = 5.8.0-2-MANJARO #1 SMP PREEMPT Sat Aug 8 17:55:27 UTC 2020 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-5.8-x86_64 root=UUID=8f0c5798-30a8-48cc-a3a6-946931575fde rw quiet splash cryptdevice=UUID=0e50bd5c-9bf0-41f8-b214-acd72c5b44f0:luks-0e50bd5c-9bf0-41f8-b214-acd72c5b44f0 root=/dev/mapper/luks-0e50bd5c-9bf0-41f8-b214-acd72c5b44f0 apparmor=1 security=apparmor resume=/dev/mapper/luks-1f444244-e194-4140-98b4-42ec6f60c99d udev.log_priority=3
Init system    = systemd 
Boot mode      = UEFI

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 21:19:10,     32 sec(s) ago
Mode           = AC
Power source   = battery

Warning: systemd-rfkill.service is not masked -- invoke "systemctl mask systemd-rfkill.service" to correct this!
Warning: systemd-rfkill.socket is not masked -- invoke "systemctl mask systemd-rfkill.socket" to correct this!
```

```
aug   19 21:27:26 mikk-thinkpad tlp[59655]: parse_args4config: tlp auto
aug   19 21:27:26 mikk-thinkpad tlp[59655]: get_sys_power_supply(AC).ac_online: syspwr=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: +++ auto (1.4.0-alpha.0) ++++++++++++++++++++++++++++++++++++++++
aug   19 21:27:26 mikk-thinkpad tlp[59655]: PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
aug   19 21:27:26 mikk-thinkpad tlp[59655]: power_source=ac
aug   19 21:27:26 mikk-thinkpad tlp[59655]: manual_mode=none
aug   19 21:27:26 mikk-thinkpad tlp[59655]: power_mode=ac
aug   19 21:27:26 mikk-thinkpad tlp[59655]: lock_tlp_nb().success
aug   19 21:27:26 mikk-thinkpad tlp[59655]: compare_and_save_power_state(0).different: old=1
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_laptopmode(0): 0; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_dirty_parms(0): 1500; ec=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_cpu_scaling_governor(0).not_configured
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_cpu_scaling_min_max_freq(0).not_configured
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_intel_cpu_perf_policy(0).hwp_epp.unsupported_cpu
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_intel_cpu_perf_policy(0).epb.unsupported_cpu
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_intel_cpu_perf_pct(0).no_intel_pstate
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_cpu_boost_all(0).not_configured
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_sched_powersave(0).not_available
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_nmi_watchdog: 0; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_phc_controls.not_configured
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_disk_apm_level(0)
aug   19 21:27:26 mikk-thinkpad tlp[59655]: get_disk_dev(nvme0n1): dev=nvme0n1; type=nvme; path=pci-0000:01:00.0-nvme-1; bus=; dpath=
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_disk_apm_level(0): nvme0n1 [] 254; not supported
aug   19 21:27:26 mikk-thinkpad tlp[59655]: get_disk_dev(sda).missing
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_disk_spindown_timeout(0).not_configured
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_disk_iosched
aug   19 21:27:26 mikk-thinkpad tlp[59655]: get_disk_dev(nvme0n1): dev=nvme0n1; type=nvme; path=pci-0000:01:00.0-nvme-1; bus=; dpath=
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_disk_iosched: nvme0n1 [] keep; keep as is
aug   19 21:27:26 mikk-thinkpad tlp[59655]: get_disk_dev(sda).missing
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_sata_link_power(0).not_available
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_ahci_runtime_pm(0).not_configured
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_pcie_aspm(0).disabled_by_kernel
aug   19 21:27:26 mikk-thinkpad tlp[59655]: check_intel_gpu.no_gpu
aug   19 21:27:26 mikk-thinkpad tlp[59655]: check_amd_gpu.present: drv=amdgpu; drm=/sys/class/drm/card0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_radeon_profile(0).not_available
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_wifi_power_mode(0, wlp3s0).iw: off; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: disable_wake_on_lan: enp2s0f0; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: disable_wake_on_lan: enp5s0; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_sound_power_mode(0).hda: 1; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_sound_power_mode(0).hda_controller: Y; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:00.0 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:00.2 [0x080600]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:01.0 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:02.0 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:02.1 [0x060400]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:02.2 [0x060400]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:02.3 [0x060400]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:02.4 [0x060400]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:02.6 [0x060400]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:02.7 [0x060400]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:08.0 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:08.1 [0x060400]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:14.0 [0x0c0500]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:14.3 [0x060100]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.0 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.1 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.2 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.3 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.4 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.5 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.6 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:00:18.7 [0x060000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:01:00.0 [0x010802]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:02:00.0 [0x020000]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:02:00.1 [0x070002]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:02:00.2 [0x070002]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:02:00.3 [0x0c0701]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:02:00.4 [0x0c0320]; rc=0
aug   19 21:27:26 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:03:00.0 [0x028000]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:04:00.0 [0xff0000]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:05:00.0 [0x020000]; rc=0
aug   19 21:27:27 mikk-thinkpad kernel: usb usb2: root hub lost power or was reset
aug   19 21:27:27 mikk-thinkpad kernel: usb usb3: root hub lost power or was reset
aug   19 21:27:27 mikk-thinkpad kernel: xhci_hcd 0000:06:00.0: Zeroing 64bit base registers, expecting fault
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:06:00.0 [0x0c0330]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:07:00.0 [0x030000]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:07:00.1 [0x040300]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:07:00.2 [0x108000]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:07:00.3 [0x0c0330]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:07:00.4 [0x0c0330]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:07:00.5 [0x048000]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_runtime_pm(0).on: /sys/bus/pci/devices/0000:07:00.6 [0x040300]; rc=0
aug   19 21:27:27 mikk-thinkpad tlp[59655]: poweroff_drivebay(0).disabled
aug   19 21:27:27 mikk-thinkpad tlp[59655]: set_radio_device_states(0): enable= disable=
aug   19 21:27:27 mikk-thinkpad tlp[59655]: save_runconf.ok: /run/tlp/tlp-run.conf_tmpOlGbtc -> /run/tlp/run.conf
aug   19 21:27:27 mikk-thinkpad tlp[59655]: unlock_tlp()
aug   19 21:27:27 mikk-thinkpad tlp[59873]: parse_args4config: tlp auto
aug   19 21:27:27 mikk-thinkpad tlp[59873]: get_sys_power_supply(AC).ac_online: syspwr=0
aug   19 21:27:27 mikk-thinkpad tlp[59873]: +++ auto (1.4.0-alpha.0) ++++++++++++++++++++++++++++++++++++++++
aug   19 21:27:27 mikk-thinkpad tlp[59873]: PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
aug   19 21:27:27 mikk-thinkpad tlp[59873]: power_source=ac
aug   19 21:27:27 mikk-thinkpad tlp[59873]: manual_mode=none
aug   19 21:27:27 mikk-thinkpad tlp[59873]: power_mode=ac
aug   19 21:27:27 mikk-thinkpad tlp[59873]: lock_tlp_nb().success
aug   19 21:27:27 mikk-thinkpad tlp[59873]: compare_and_save_power_state(0).equal
aug   19 21:27:27 mikk-thinkpad tlp[59873]: unlock_tlp()
aug   19 21:27:27 mikk-thinkpad tlp[59901]: parse_args4config: tlp auto
aug   19 21:27:27 mikk-thinkpad tlp[59901]: get_sys_power_supply(AC).ac_online: syspwr=0
aug   19 21:27:27 mikk-thinkpad tlp[59901]: +++ auto (1.4.0-alpha.0) ++++++++++++++++++++++++++++++++++++++++
aug   19 21:27:27 mikk-thinkpad tlp[59901]: PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
aug   19 21:27:27 mikk-thinkpad tlp[59901]: power_source=ac
aug   19 21:27:27 mikk-thinkpad tlp[59901]: manual_mode=none
aug   19 21:27:27 mikk-thinkpad tlp[59901]: power_mode=ac
aug   19 21:27:27 mikk-thinkpad tlp[59901]: lock_tlp_nb().success
aug   19 21:27:27 mikk-thinkpad tlp[59901]: compare_and_save_power_state(0).equal
aug   19 21:27:27 mikk-thinkpad tlp[59901]: unlock_tlp()

```
I do not think it works.. It finds that it has GPU with drv=amdgpu

but it does not try to set performance levels on radeon OR amdgpu, because you check if device sysfs full path is equal to either `amdgpu` or `radeon` which NEVER can be the case

**Comment by mikk150** [comment]
also, what if I have Zephyrs G14, where you have 2 GPUs, one with amdgpu driver, and other with nouveau driver. sice you are not checking if DRM you are currently on is amdgpu device, you try to put nonsense into nouveau driver

**Comment by linrunner** [comment]
My bad. Please try again.

**Comment by mikk150** [comment]
this should work.
But what is the purpose of `check_amd_gpu` when it does effectively same job as `set_amdgpu_profile` exaclty the same way(loop over all available DRM-s)?

**Comment by mikk150** [comment]
```

12:05 $ sudo tlp-stat -s -g
--- TLP 1.4.0-alpha.0 --------------------------------------------

+++ System Info
System         = LENOVO ThinkPad T14 Gen 1 20UDCTO1WW
BIOS           = R1BET36W(1.05 )
Release        = "Manjaro Linux"
Kernel         = 5.8.0-2-MANJARO #1 SMP PREEMPT Sat Aug 8 17:55:27 UTC 2020 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-5.8-x86_64 root=UUID=8f0c5798-30a8-48cc-a3a6-946931575fde rw quiet splash cryptdevice=UUID=0e50bd5c-9bf0-41f8-b214-acd72c5b44f0:luks-0e50bd5c-9bf0-41f8-b214-acd72c5b44f0 root=/dev/mapper/luks-0e50bd5c-9bf0-41f8-b214-acd72c5b44f0 apparmor=1 security=apparmor resume=/dev/mapper/luks-1f444244-e194-4140-98b4-42ec6f60c99d udev.log_priority=3
Init system    = systemd 
Boot mode      = UEFI

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 12:04:57,     50 sec(s) ago
Mode           = battery
Power source   = battery

Warning: systemd-rfkill.service is not masked -- invoke "systemctl mask systemd-rfkill.service" to correct this!
Warning: systemd-rfkill.socket is not masked -- invoke "systemctl mask systemd-rfkill.socket" to correct this!

+++ AMD Radeon Graphics (amdgpu)
/sys/class/drm/card0/device/power_dpm_force_performance_level     = low

```

**Comment by linrunner** [comment]
> But what is the purpose of check_amd_gpu when it does effectively same job as set_amdgpu_profile exaclty the same way(loop over all available DRM-s?

The question is legitimate. But i'm not finished yet. I wonder if i should show all graphics cards in tlp-stat.

Could you show me

    ls -lR  /sys/class/drm/card?/device/

for your machine? Via https://gist.github.com/ please.

**Comment by mikk150** [comment]
> > Zephyrus G14, where you have 2 GPUs, one with amdgpu driver, and other with nouveau driver
> 
> I don't see card1 in the output?!

I never said I had it...

**Comment by mikk150** [comment]
https://gist.github.com/mikk150/ff26b25f2ba35e9830ff8d7d66efc424
https://gist.github.com/mikk150/5569dc77ed29ea0c87921f1fcd86d52f

**Comment by mikk150** [comment]
root@ubuntu:/sys/kernel/debug/dri/1# cat pstate 
07: core 270-405 MHz memory 810 MHz
0f: core 270-950 MHz memory 1800 MHz
AC: core 0 MHz memory 0 MHz

This should be interesting as well

**Comment by linrunner** [comment]
> https://gist.github.com/mikk150/ff26b25f2ba35e9830ff8d7d66efc424
> https://gist.github.com/mikk150/5569dc77ed29ea0c87921f1fcd86d52f

Thanks. Seems to work as designed.

> root@ubuntu:/sys/kernel/debug/dri/1# cat pstate

Nvidia w/ nouveau only? Or amdgpu too?

The amdgpu laptop still works after the refactoring? tlp-stat output?

**Comment by mikk150** [comment]
> > https://gist.github.com/mikk150/ff26b25f2ba35e9830ff8d7d66efc424
> > https://gist.github.com/mikk150/5569dc77ed29ea0c87921f1fcd86d52f
> 
> Thanks. Seems to work as designed.
> 
> > root@ubuntu:/sys/kernel/debug/dri/1# cat pstate
> 
> Nvidia w/ nouveau only? Or amdgpu too?
> 
> The amdgpu laptop still works after the refactoring? tlp-stat output?

Only on nouveau

https://gist.github.com/mikk150/f34b59dd08c5f6477deb1379d70f60ae

This is on amdgpu

**Comment by linrunner** [comment]
Thanks. 

I also need the tlp-stat output for amdgpu please.

**Comment by mikk150** [comment]
```
--- TLP 1.4.0-alpha.0 --------------------------------------------

+++ System Info
System         = LENOVO ThinkPad T14 Gen 1 20UDCTO1WW
BIOS           = R1BET36W(1.05 )
Release        = "Manjaro Linux"
Kernel         = 5.8.1-3-MANJARO #1 SMP PREEMPT Sat Aug 15 19:17:30 UTC 2020 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-5.8-x86_64 root=UUID=8f0c5798-30a8-48cc-a3a6-946931575fde rw quiet splash pcie_aspm=force cryptdevice=UUID=0e50bd5c-9bf0-41f8-b214-acd72c5b44f0:luks-0e50bd5c-9bf0-41f8-b214-acd72c5b44f0 root=/dev/mapper/luks-0e50bd5c-9bf0-41f8-b214-acd72c5b44f0 apparmor=1 security=apparmor resume=/dev/mapper/luks-1f444244-e194-4140-98b4-42ec6f60c99d udev.log_priority=3
Init system    = systemd 
Boot mode      = UEFI

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 22:42:47,     94 sec(s) ago
Mode           = battery
Power source   = battery

Warning: systemd-rfkill.service is not masked -- invoke "systemctl mask systemd-rfkill.service" to correct this!
Warning: systemd-rfkill.socket is not masked -- invoke "systemctl mask systemd-rfkill.socket" to correct this!

+++ AMD Radeon Graphics
/sys/class/drm/card0/device/driver           = amdgpu
/sys/class/drm/card0/device/power_dpm_force_performance_level     = low
```

**Comment by linrunner** [comment]
Fine. Thank you very much for your help so far.

I will not implement the nouveau pstate for the time being, otherwise users will think they can control the frequencies with TLP although the feature does not exist.

**Comment by mikk150** [comment]
BTW you can change pstates on nouveau and it works

**Comment by linrunner** [comment]
If the configuration is understandable for end users, i'd welcome a pull request. 

I have only hardware with Intel GPUs. As a matter of principle i do not buy Nvidia hardware ...

**Comment by linrunner** [comment]
> I think it does not work on 900 and up series cards
What hardware release year is this?

**Comment by mikk150** [comment]
> If the configuration is understandable for end users, i'd welcome a pull request.
> 
> I have only hardware with Intel GPUs. As a matter of principle i do not buy Nvidia hardware ...

I do not buy any Nvidia hardware as well, I had very very bad experience with it when I used this laptop, now it just sits in the corner



> > I think it does not work on 900 and up series cards
> 
> What hardware release year is this?

2014

**Comment by linrunner** [comment]
> 2014

Then it is probably not worth it.

**Comment by userofryzen** [comment]
I come to this mr after months because of time and I see it's merged and completed,  okey, thanks @linrunner for all and everyone involved on this!:)

**Comment by bdaase** [comment]
Does anyone know why the output of `/sys/class/drm/card0/device/power_dpm_force_performance_level` is `auto` for me in battery mode instead of `low`?

```
(base) ➜  ~ sudo tlp-stat -s -g                                                          
Place your right index finger on the fingerprint reader
--- TLP 1.4.0 --------------------------------------------

+++ System Info
System         = LENOVO ThinkPad P14s Gen 2a 21A1S00D00
BIOS           = R1MET42W (1.12 )
OS Release     = Fedora Linux 35 (Workstation Edition)
Kernel         = 5.14.17-301.btusbhang1.fc35.x86_64 #1 SMP Tue Nov 9 16:57:10 UTC 2021 x86_64
/proc/cmdline  = BOOT_IMAGE=(hd0,gpt2)/vmlinuz-5.14.17-301.btusbhang1.fc35.x86_64 root=UUID=9641d196-a942-4f26-b1ff-61c0473b9984 ro rootflags=subvol=@ rhgb quiet
Init system    = systemd 
Boot mode      = UEFI
SELinux status = enabled (enforcing)

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 23:17:32,    763 sec(s) ago
Mode           = battery
Power source   = battery

+++ AMD Radeon Graphics
/sys/class/drm/card0/device/driver                                = amdgpu

/sys/class/drm/card0/device/power_dpm_force_performance_level     = auto
```

**Pull request merged**
