### PR TITLE
Added verbose mode, battery cell group voltage in verbose mode

### PR DESCRIPTION
**Pull request by yutzhead**
Shows the battery group cell voltage when called with -v

### CODE REVIEW

**Comment by linrunner** [comment]
Hi,

thanks for your pull request. 

Before you continue to add GUI features to your pull request: i won't merge them in this project.

Nevertheless there is a config GUI for TLP in preparation, written by a another user, where your work will fit much better. Unfortunately it's not yet on Github. So keep your code and stay tuned please.

What i'd like to merge is your first feature https://github.com/yutzhead/TLP/commit/269704a0e7925acba0e59f2d9c2d3dc5428acde1 . Please rebase it to the **devel** branch.

**Comment by linrunner** [comment]
TLPUI project is now online: https://github.com/d4nj1/TLPUI :-)

**Comment by yutzhead** [comment]
Yeah hi,
I only wanted to merge the first commit to begin with.

**Comment by d4nj1** [comment]
I hope that TLPUI will be more than just a config editor in the future. I would love to have tlp-stat output visualized in the UI.

**Comment by linrunner** [comment]
Merged 269704a by hand. 

**Please base further requests on branch devel!**

**Pull request closed without merging**
