### PR TITLE
Add the output PCI device running status information -v2.0

### PR DESCRIPTION
**Pull request by sujiaxun**
Signed-off-by: sujiaxun <sujiaxun@uniontech.com>

### CODE REVIEW

**Comment by sujiaxun** [comment]
[https://github.com/linrunner/TLP/pull/559](url)

**Comment by sujiaxun** [comment]
[https://github.com/linrunner/TLP/pull/559](url)

**Comment by sujiaxun** [comment]
https://github.com/linrunner/TLP/pull/559

**Comment by linrunner** [comment]
Thank you.

**Pull request merged**
